#!/bin/sh
curl "https://tibiawiki.com.br/wiki/Capacetes" -o "Capacetes.html"
curl "https://tibiawiki.com.br/wiki/Armaduras" -o "Armaduras.html"
curl "https://tibiawiki.com.br/wiki/Escudos" -o "Escudos.html"
curl "https://tibiawiki.com.br/wiki/Cal%C3%A7as" -o "Calças.html"
curl "https://tibiawiki.com.br/wiki/Spellbooks" -o "Spellbooks.html"
curl "https://tibiawiki.com.br/wiki/Botas" -o "Botas.html"
curl "https://tibiawiki.com.br/wiki/Machados" -o "Machados.html"
curl "https://tibiawiki.com.br/wiki/Clavas" -o "Clavas.html"
curl "https://tibiawiki.com.br/wiki/Espadas" -o "Espadas.html"
curl "https://tibiawiki.com.br/wiki/Rods" -o "Rods.html"
curl "https://tibiawiki.com.br/wiki/Wands" -o "Wands.html"
curl "https://tibiawiki.com.br/wiki/Antigas_Wands_e_Rods" -o "Antigas Wands e Rods.html"
curl "https://tibiawiki.com.br/wiki/Dist%C3%A2ncia" -o "Distância.html"
curl "https://tibiawiki.com.br/wiki/R%C3%A9plicas#R.C3.A9plicas_de_Armas" -o "Réplicas.html"
curl "https://tibiawiki.com.br/wiki/Livros" -o "Livros.html"
curl "https://tibiawiki.com.br/wiki/Pr%C3%AAmios_de_Eventos" -o "Prêmios de Eventos.html"
curl "https://tibiawiki.com.br/wiki/Runas_de_Decora%C3%A7%C3%A3o" -o "Runas de Decoração.html"
curl "https://tibiawiki.com.br/wiki/Documentos_e_Pap%C3%A9is" -o "Documentos e Papéis.html"
curl "https://tibiawiki.com.br/wiki/Dolls_e_Bears" -o "Dolls e Bears.html"
curl "https://tibiawiki.com.br/wiki/Decora%C3%A7%C3%B5es" -o "Decorações.html"
curl "https://tibiawiki.com.br/wiki/Instrumentos_Musicais" -o "Instrumentos Musicais.html"
curl "https://tibiawiki.com.br/wiki/Trof%C3%A9us" -o "Troféus.html"
curl "https://tibiawiki.com.br/wiki/Itens_de_Fansites" -o "Itens de Fansites.html"
curl "https://tibiawiki.com.br/wiki/Comidas" -o "Comidas.html"
curl "https://tibiawiki.com.br/wiki/L%C3%ADquidos" -o "Líquidos.html"
curl "https://tibiawiki.com.br/wiki/Plantas_e_Ervas" -o "Plantas e Ervas.html"
curl "https://tibiawiki.com.br/wiki/Produtos_de_Criaturas" -o "Produtos de Criaturas.html"
curl "https://tibiawiki.com.br/wiki/Amuletos_e_Colares" -o "Amuletos e Colares.html"
curl "https://tibiawiki.com.br/wiki/An%C3%A9is" -o "Anéis.html"
curl "https://tibiawiki.com.br/wiki/Chaves" -o "Chaves.html"
curl "https://tibiawiki.com.br/wiki/Ferramentas" -o "Ferramentas.html"
curl "https://tibiawiki.com.br/wiki/Ferramentas_de_Cozinha" -o "Ferramentas de Cozinha.html"
curl "https://tibiawiki.com.br/wiki/Fontes_de_Luz" -o "Fontes de Luz.html"
curl "https://tibiawiki.com.br/wiki/Itens_de_Domar" -o "Itens de Domar.html"
curl "https://tibiawiki.com.br/wiki/Recipientes" -o "Recipientes.html"
curl "https://tibiawiki.com.br/wiki/Itens_de_Addons" -o "Itens de Addons.html"
curl "https://tibiawiki.com.br/wiki/Itens_Encantados" -o "Itens Encantados.html"
curl "https://tibiawiki.com.br/wiki/Jogos_e_Divers%C3%A3o" -o "Jogos e Diversão.html"
curl "https://tibiawiki.com.br/wiki/Itens_de_Quest" -o "Itens de Quest.html"
curl "https://tibiawiki.com.br/wiki/Cristais_(Itens)" -o "Cristais (Itens).html"
curl "https://tibiawiki.com.br/wiki/Itens_de_Festa" -o "Itens de Festa.html"
curl "https://tibiawiki.com.br/wiki/Valiosos" -o "Valiosos.html"
curl "https://tibiawiki.com.br/wiki/Lixos" -o "Lixos.html"
curl "https://tibiawiki.com.br/wiki/Runas" -o "Runas.html"
